name: handbook
channels:
  - conda-forge
dependencies:
  # Packages required for setting up the environment
  - pip>=21
  - python>=3.12,<3.13

  # Use pip to install the package defined by this repo for development:
  - pip:
      - --editable ./
