name: handbook
channels:
  - conda-forge
  - defaults
dependencies:
  # Packages required for setting up the environment
  - pip>=21,<24
  - python>=3.10,<3.11
  - setuptools<66

  # Use pip to install the package defined by this repo for development:
  - pip:
      - --editable ./
